# Generated by Django 4.0.2 on 2022-02-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
